on:
  schedule:
      - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  bililive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: node index.js
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Initial commit
          branch: master
          commit_options: --amend
          file_pattern: bililive.m3u
          push_options: --force
